services:
  mininet:
    build: .
    container_name: mininet
    tty: true
    command: tail -f /dev/null # Keep the container running for CLI access
    networks:
      - net
    volumes:
      - ./topology.py:/topology.py
      - pcap:/mnt/pcap # A share volume, access output from other services
      - ./shared_volume:/mnt/pcap

  attacker:
    image: ubuntu:20.04
    container_name: attacker
    tty: true
    networks:
      - net
    command: tail -f /dev/null # Keep the container running for CLI access
    depends_on:
      - mininet
    volumes:
      - ./ddos_attack.sh:/ddos_attack.sh

  processor:
    build: ./docker/processor
    container_name: processor
    tty: true
    networks:
      - net
    depends_on:
      - mininet
    volumes:
      - ./process_pcap.py:/app/process_pcap.py
      - pcap:/mnt/pcap
      - ./shared_volume:/mnt/pcap
    command: python /app/process_pcap.py

networks:
  net:
    driver: bridge

volumes:
  pcap: